### ISSUE TITLE
war3zuk

### ISSUE THREAD

**Issue by erictr8** [War3zuk/War3zuk-Alpha-19-Stable-AIO#2]
constant crash on new 7 days to die alpha 19 up date

**Comment by War3zuk** [comment]
you need to be on a fresh install of the mod & game... or delete prefabs folder & verify files with steam... if launcher delete complete & reinstall

**Comment by erictr8** [comment]
Ok thank u

**Comment by erictr8** [comment]
I reinstalled everything and updated alpha 19 to latest build and redownloaded mod launcher.i am logged into my steam account i yry to launch the mod but comes up that im not logged into steam and will not let me play

**Comment by erictr8** [comment]
![1595130207346991251099363664339](https://user-images.githubusercontent.com/68461032/87866498-825e3480-c950-11ea-9ab2-27fe02050312.jpg)

**Comment by War3zuk** [comment]
You need to a fresh install or verify steam game... then delete complete on
launcher then install... your steam is on 169 your launcher files are b163

**Comment by erictr8** [comment]
I got now thank u.  some files wanted to be stubborn and not delete

**Comment by War3zuk** [comment]
Cool glad you have it working

**Comment by erictr8** [comment]
Me to its the best mod there is out
