### ISSUE TITLE
How to make a War3zuk dedicated Server (on Linux) ?

### ISSUE THREAD

**Issue by BamDelicious** [War3zuk/War3zuk-Alpha-19-Stable-AIO#3]
Tried to copy all mods from "C:\7D2D\Alpha19\War3zuk\War3zuk_Alpha_19_AIO_OverHaul\Mods" to the Mods-Folder on the Server, but got 1000's of errors

**Comment by War3zuk** [comment]
Then id suggest you do it properly cos uve done something wrong as these files have no startup errors..

**Comment by BamDelicious** [comment]
but is that the way to go? copy mod-folder to mod-folder?

**Comment by War3zuk** [comment]
Fresh install of Alpha 19 B173 then add the standalone mod to the Mods folder.. Or download the 7 days to die mod launcher & install the mod from the left hand side making sure your steam is on a clean install of B173

**Comment by BamDelicious** [comment]
and on the dedicated server side? I'm using the ModLauncher on Clientside

**Comment by War3zuk** [comment]
https://gitlab.com/war3zuk/War3zuk-Alpha-19-AIO-Mod-Launcher_2020

Open the Rar youll see 2 folders, Data & Mods.... Log into your server youll be at its base directory, Drag those 2 folders onto it & upload when asked to over write click yes to all.. Once done Boot server up in a fresh world

If you wish to use the Custom map then you need to copy & paste the folder name to the following in your serverconfig.xml file

  <property name="GameWorld" 			value="War3zukAIOAlpha19"/>
  <property name="WorldGenSeed" 		value="War3zukAIOAlpha19"/>
  <property name="WorldGenSize" 			value="8192"/>
  <property name="GameName" 			value="War3zukAIOAlpha19"/>

**Comment by War3zuk** [comment]
<property name="GameWorld" 				value="War3zukAIOAlpha19"/>
  <property name="WorldGenSeed" 			value="War3zukAIOAlpha19"/>
  <property name="WorldGenSize" 				value="8192"/>
  <property name="GameName" 				value="War3zukAIOAlpha19"/>
