### ISSUE TITLE
Options issue

### ISSUE THREAD

**Issue by WhoopAssFMS** [War3zuk/War3zuk-Alpha-19-Stable-AIO#8]
Installed mod and it plays fine but cannot enter options menu and also accepting a party invite starts a list of errors
![options error](https://user-images.githubusercontent.com/85129919/120228909-b0b7cc00-c211-11eb-9186-029b6f47342b.jpg)

**Comment by War3zuk** [comment]
New stable = completely fresh install & game...no old files

**Comment by WhoopAssFMS** [comment]
so which one of these do i use? one is the aio full installer and which is the data and mods folder, or is it the files from here ?      
![whichone - Copy](https://user-images.githubusercontent.com/85129919/120233878-5c661980-c21c-11eb-8d26-da698537d373.png)

**Comment by War3zuk** [comment]
Launcher version adds custom prefabs..zombies & tweaks along with my overhaul... the other is just my overhaul on its own..
